# Generated by rust2rpm 26
%bcond_without check

%define zed_version 0.137.6

Name:           zed
Version:        %{zed_version}
Release:        %autorelease
Summary:        Fast, collaborative code editor

SourceLicense:  AGPL-3.0-or-later AND Apache-2.0 AND GPL-3.0-or-later
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            https://zed.dev/
Source:         https://github.com/zed-industries/zed/archive/refs/tags/v%{zed_version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  gcc
BuildRequires:  g++
BuildRequires:  alsa-lib-devel
BuildRequires:  fontconfig-devel
BuildRequires:  wayland-devel
BuildRequires:  libxkbcommon-x11-devel
BuildRequires:  openssl-devel
BuildRequires:  libzstd-devel
BuildRequires:  perl-FindBin
BuildRequires:  perl-IPC-Cmd
BuildRequires:  perl-File-Compare
BuildRequires:  perl-File-Copy
BuildRequires:  perl-lib
BuildRequires:  vulkan-loader

Requires:  alsa-lib
Requires:  fontconfig
Requires:  openssl
Requires:  libzstd
Requires:  vulkan-loader

%global _description %{expand:
The fast, collaborative code editor.}

%description %{_description}

%prep
%autosetup -n zed-%{version} -p1
# Modified %%cargo_prep
(
    set -euo pipefail
    /usr/bin/mkdir -p target/rpm
    /usr/bin/ln -s rpm target/release
    /usr/bin/rm -rf .cargo/
    /usr/bin/mkdir -p .cargo
    cat > .cargo/config.toml << EOF
[build]
rustc = "/usr/bin/rustc"
rustdoc = "/usr/bin/rustdoc"
# v0 mangling scheme provides more detailed backtraces around closures
rustflags = ["-C", "symbol-mangling-version=v0", "--cfg", "tokio_unstable"]

[alias]
xtask = "run --package xtask --"

[profile.rpm]
inherits = "release"
opt-level = 3
codegen-units = 1
debug = 2
strip = "none"

[env]
CFLAGS = "-O2 -g"
CXXFLAGS = "-O2 -g"
LDFLAGS = "%{build_ldflags}"

[install]
root = "%{buildroot}/usr"

[term]
verbose = true

EOF
    /usr/bin/rm -f Cargo.lock
    /usr/bin/rm -f Cargo.toml.orig
)

# %%build
# %%cargo_build
# %%{cargo_license_summary}
# %%{cargo_license} > LICENSE.dependencies

%install
# Adapted %%cargo_install
(
    set -euo pipefail
    /usr/bin/env CARGO_HOME=.cargo RUSTC_BOOTSTRAP=1 RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Cforce-frame-pointers=yes --cap-lints=warn' /usr/bin/cargo install -j${RPM_BUILD_NCPUS} -Z avoid-dev-deps --profile rpm --no-track --path crates/%{name}
)
# FIXME: install shared library

# %%if %{with check}
# %%check
# %%cargo_test
# %%endif

%files
%license LICENSE-AGPL
%license LICENSE-APACHE
%license LICENSE-GPL
# %%license LICENSE.dependencies
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/Zed

%changelog
%autochangelog
